# 1. | top level
# 1.1  absolute path
@include $HOME/Projects/fluentd-docs/configuration/examples/configFile/filter/configFile.conf

# relative path, the directive will use
# the dirname of this config file to expand the path
@include ../filter/configFile.conf

# 1.2 glob match pattern
@include config.d/*.conf

# 1.3 http
@include http://example.com/fluent.conf

# 2. subsections
<match pattern>
  @type forward
  # ...
  <buffer>
    @type file
    path /path/to/buffer/forward
    @include /path/to/out_buf_params.conf
  </buffer>
</match>
