# add it to test the filter
<source>
  @type http
  port 9880
</source>

# ALTHOUGH you hit with tag "foo.bar", event is NOT processed       --  Solution: add <match>
<filter foo.bar>
  @type record_transformer
  <record>
    hostname "#{Socket.gethostname}"
    tag ${tag}
  </record>
</filter>
