# 1.1 *
<match myapp.*>        # match events / tagged -- with -- "myapp.*"   --  matches: `a.b`, NOT match `a` or `a.b.c` --
  @type file
  path /var/log/fluent/access
</match>

# 1.2 **
<match myapp.**>        # match events / tagged -- with -- "myapp.**"   --  matches: `a.b`, `a`, `a.b.c` --
  @type file
  path /var/log/fluent/access
</match>

# 1.3 {X,Y,Z}
<match myapp.{a,b}>        # match events / tagged -- with -- "myapp.{a,b}"   --  matches: `a`, `b`, NOT match: `c` --
  @type file
  path /var/log/fluent/access
</match>

# 1.4.1 {X,Y,Z} + *
<match myapp.{a,b}.*>
  @type file
  path /var/log/fluent/access
</match>

# 1.4.2 {X,Y,Z} + **
<match myapp.{a,**}>
  @type file
  path /var/log/fluent/access
</match>

# 1.5 regular expressions
<match myapp./(?!a\.).*/>           # TODO:
  ...
</match>

# 1.6 embed Ruby expressions
<match "app.#{ENV['FLUENTD_TAG']}">           # match: `a` & `b`
  ...
</match>

# 2. MULTIPLE patterns
<match a b>           # match: `a` & `b`        separated by " "
  ...
</match>
