# 1. order to match tags    ==      order | config file
<match **>      # match ALL tags -> NEXT one is NEVER matched
  @type blackhole_plugin
</match>

<match myapp.access>
  @type file
  path /var/log/fluent/access
</match>
```

# 2. <filter> MUST NOT be placed BEFORE <match>

<filter myapp.access>
  @type record_transformer
  ...
</filter>

<match myapp.access>
  @type file
  path /var/log/fluent/access
</match>
