# Receive events from 24224/tcp
# This is used by log forwarding and the fluent-cat command
<source>
  @type forward
  port 24224
</source>

# http://<ip>:9880/myapp.access?json={"event":"data"}
<source>
  @type http
  port 9880
</source>

<match myapp.access>        # match events / tagged -- with -- "myapp.access"
  @type file                        # store the events | "/var/log/fluent/access.%Y-%m-%d"
  path /var/log/fluent/access
</match>
