## 1. Content-Type: application/x-www-form-urlencoded -> specify data format -- via -- prefix
## 1.1          json=
### POST JSON data -- via -- tag == "app.log"
POST http://localhost:9880/app.log
Content-Type: application/x-www-form-urlencoded

json={"foo":"bar"}

## 1.2          ndjson=
### post NDJSON data -- via -- tag == "app.log"
POST http://localhost:9880/app.log
Content-Type: application/x-www-form-urlencoded

ndjson={"k1":"v1"}
{"k2":"v2"}

## 1.3          msgpack=
# TODO: incoming event is invalid
### post MessagePack data -- via -- tag == "app.log"
POST http://localhost:9880/app.log
Content-Type: application/x-www-form-urlencoded

msgpack=msgpack=\x81\xa3foo\xa3bar

## 2. Content-Type: application/json        -> NO required to specify the format
### 2.1 POST JSON data -- via -- tag == "app.log"
POST http://localhost:9880/app.log
Content-Type: application/json

{"foo":"bar"}

### 3. time parameter   -> override default one
POST http://localhost:9880/app.log?time=1518756037.3137116
Content-Type: application/json

{"foo":"bar"}

### 4. if request set MULTIPLE request's headers `X-Forwarded-For` -> `in_http` uses the FIRST one
POST http://localhost:9880/app.log
Content-Type: application/json
X-Forwarded-For: host1, host2
X-Forwarded-For: host3

{"foo":"bar"}
