# add it to test the filter
<source>
  @type http
  port 9880
</source>

<filter foo.bar>
  @type record_transformer
  <record>
    hostname "#{Socket.gethostname}"
    tag ${tag}
  </record>
</filter>

# TODO: add <match>
